service:
  db:
    container_name: postgres
    image: postgres
    enviroment:
      POSTGRES_USER: gersimuca
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    network:
      -db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: